symfony/src/Entity/Joueur.php
<?php

namespace App\Entity;

use App\Repository\JoueurRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;

#[ORM\Entity(repositoryClass: JoueurRepository::class)]
#[ApiResource]
class Joueur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $nationalite = null;

    #[ORM\ManyToOne(inversedBy: 'joueurs')]
    private ?Equipe $equipe = null;

    /**
     * @param int|null $id
     * @param string|null $nom
     * @param string|null $prenom
     * @param \DateTimeInterface|null $date_naissance
     * @param string|null $nationalite
     */
    public function __construct(?string $nom = '', ?string $prenom= '', ?\DateTimeInterface $date_naissance = new \DateTime(), ?string $nationalite = '')
    {
        $aujourdhui = new \DateTime();
        $date_naissance_valide = $date_naissance && $date_naissance <= $aujourdhui && $date_naissance->format('Y') >= 1900;

        // Si la date de naissance n'est pas valide, lance une exception
        if (!$date_naissance_valide) {
            throw new \InvalidArgumentException('La date de naissance doit être entre 1900 et aujourd\'hui.');
        }
        $this->nom = $nom;
        $this->prenom = $prenom;
        $this->date_naissance = $date_naissance;
        $this->nationalite = $nationalite;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getEquipe(): ?Equipe
    {
        return $this->equipe;
    }

    public function setEquipe(?Equipe $equipe): self
    {
        $this->equipe = $equipe;

        return $this;
    }

}

symfony/src/Form/JoueurType.php
<?php

namespace App\Form;

use App\Entity\Joueur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JoueurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_naissance', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd/MM/yyyy',
            ])
            ->add('nationalite')
            ->add('equipe')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Joueur::class,
        ]);
    }
}

symfony/src/Controller/JoueurController.php
<?php

namespace App\Controller;

use App\Entity\Joueur;
use App\Form\JoueurType;
use App\Repository\JoueurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/joueur')]
class JoueurController extends AbstractController
{
    #[Route('/', name: 'app_joueur_index', methods: ['GET'])]
    public function index(JoueurRepository $joueurRepository): Response
    {
        return $this->render('joueur/index.html.twig', [
            'joueurs' => $joueurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_joueur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, JoueurRepository $joueurRepository): Response
    {
        $joueur = new Joueur();
        $form = $this->createForm(JoueurType::class, $joueur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $joueurRepository->save($joueur, true);

            return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('joueur/new.html.twig', [
            'joueur' => $joueur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_joueur_show', methods: ['GET'])]
    public function show(Joueur $joueur): Response
    {
        return $this->render('joueur/show.html.twig', [
            'joueur' => $joueur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_joueur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Joueur $joueur, JoueurRepository $joueurRepository): Response
    {
        $form = $this->createForm(JoueurType::class, $joueur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $joueurRepository->save($joueur, true);

            return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('joueur/edit.html.twig', [
            'joueur' => $joueur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_joueur_delete', methods: ['POST'])]
    public function delete(Request $request, Joueur $joueur, JoueurRepository $joueurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$joueur->getId(), $request->request->get('_token'))) {
            $joueurRepository->remove($joueur, true);
        }

        return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
    }
}

symfony/templates/joueur/_delete_form.html.twig
<form method="post" action="{{ path('app_joueur_delete', {'id': joueur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ joueur.id) }}">
    <button class="btn">Delete</button>
</form>

symfony/templates/joueur/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

symfony/templates/joueur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Joueur{% endblock %}

{% block body %}
    <div class="container my-5">
        <h1>Edit Joueur</h1>

        {{ include('joueur/_form.html.twig', {'button_label': 'Update'}) }}

        <a class="btn btn-secondary" href="{{ path('app_joueur_index') }}">Back to list</a>

        {{ include('joueur/_delete_form.html.twig') }}
    </div>
{% endblock %}

symfony/templates/joueur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Joueurs{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/table.css') }}">
{% endblock %}

{% block body %}
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <h2>Joueurs</h2>
                <div class="btn-group">
                    <a href="{{ path('app_joueur_new') }}" class="btn add btn-primary add-new"><i class="material-icons">add</i> Add New</a>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Date_naissance</th>
                    <th>Nationalite</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for joueur in joueurs %}
                    <tr>
                        <td>{{ joueur.id }}</td>
                        <td>{{ joueur.nom }}</td>
                        <td>{{ joueur.prenom }}</td>
                        <td>{{ joueur.dateNaissance ? joueur.dateNaissance.format('d/m/Y') : '' }}</td>
                        <td>{{ joueur.nationalite }}</td>
                        <td class="actions">
                            <a href="{{ path('app_joueur_edit', { 'id': joueur.id}) }}" class="edit"><i class="material-icons" data-toggle="tooltip" title="Edit">edit</i></a>
                            <a href="{{ path('app_joueur_show', { 'id': joueur.id}) }}" class="view"><i class="material-icons" data-toggle="tooltip" title="View">visibility</i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% block javascripts %}
        <script src="{{ asset('js/scripts.js') }}" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% endblock %}
{% endblock %}

symfony/templates/joueur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Joueur{% endblock %}

{% block body %}
    <div class="container my-5">
        <h2 class="form-title">Create new Joueur</h2>

        {{ include('joueur/_form.html.twig') }}

        <a class="btn btn-secondary" href="{{ path('app_joueur_index') }}">Back to list</a>
    </div>
{% endblock %}

symfony/templates/joueur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Joueur{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="my-4">Joueur</h1>

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ joueur.id }}</td>
                    </tr>
                    <tr>
                        <th>Nom</th>
                        <td>{{ joueur.nom }}</td>
                    </tr>
                    <tr>
                        <th>Prénom</th>
                        <td>{{ joueur.prenom }}</td>
                    </tr>
                    <tr>
                        <th>Date de naissance</th>
                        <td>{{ joueur.dateNaissance ? joueur.dateNaissance.format('d/m/Y') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Nationalité</th>
                        <td>{{ joueur.nationalite }}</td>
                    </tr>
                    </tbody>
                </table>

                <div class="mt-4">
                    <a href="{{ path('app_joueur_index') }}" class="btn btn-primary mr-2">Retour à la liste</a>
                    <a href="{{ path('app_joueur_edit', {'id': joueur.id}) }}" class="btn btn-success mr-2">Modifier</a>
                    {{ include('joueur/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}