symfony/src/Entity/Tournoi.php
<?php

namespace App\Entity;

use App\Repository\TournoiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;

#[ORM\Entity(repositoryClass: TournoiRepository::class)]
#[ApiResource]
class Tournoi
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id ;

    #[ORM\Column(length: 255)]
    private ?string $nom ;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_debut ;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin ;

    #[ORM\ManyToMany(targetEntity: Equipe::class, mappedBy: 'tournoi')]
    private Collection $equipes;

    #[ORM\OneToMany(mappedBy: 'tournoi', targetEntity: Game::class, cascade: ['remove'])]
    private Collection $games;




    public function __construct($nom = '', $date_debut = new \DateTime(), $date_fin = new \DateTime())
    {

        $this->nom = $nom;
        $this->date_debut= $date_debut;
        $this->date_fin= $date_fin;
        $this->equipes = new ArrayCollection();
        $this->games = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Equipe>
     */
    public function getEquipes(): Collection
    {
        return $this->equipes;
    }

    public function addEquipe(Equipe $equipe): self
    {
        if (!$this->equipes->contains($equipe)) {
            $this->equipes->add($equipe);
            $equipe->addTournoi($this);
        }

        return $this;
    }

    public function removeEquipe(Equipe $equipe): self
    {
        if ($this->equipes->removeElement($equipe)) {
            $equipe->removeTournoi($this);
        }

        return $this;
    }




    public function __toString(): string
    {
        // TODO: Implement __toString() method.
        return $this->nom;
    }

    /**
     * @return Collection<int, Game>
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games->add($game);
            $game->setTournoi($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->removeElement($game)) {
            // set the owning side to null (unless already changed)
            if ($game->getTournoi() === $this) {
                $game->setTournoi(null);
            }
        }

        return $this;
    }

}

symfony/src/Form/TournoiType.php
<?php

namespace App\Form;

use App\Entity\Tournoi;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TournoiType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('date_debut',DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd/MM/yyyy'])
            ->add('date_fin', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd/MM/yyyy'])
            ->add('equipes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tournoi::class,
        ]);
    }
}

symfony/src/Controller/TournoiController.php
<?php

namespace App\Controller;

use App\Entity\Tournoi;
use App\Form\TournoiType;
use App\Repository\TournoiRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tournoi')]
class TournoiController extends AbstractController
{
    #[Route('/', name: 'app_tournoi_index', methods: ['GET'])]
    public function index(TournoiRepository $tournoiRepository): Response
    {
        return $this->render('tournoi/index.html.twig', [
            'tournois' => $tournoiRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_tournoi_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TournoiRepository $tournoiRepository): Response
    {
        $tournoi = new Tournoi();
        $form = $this->createForm(TournoiType::class, $tournoi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tournoiRepository->save($tournoi, true);

            return $this->redirectToRoute('app_tournoi_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tournoi/new.html.twig', [
            'tournoi' => $tournoi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournoi_show', methods: ['GET'])]
    public function show(Tournoi $tournoi): Response
    {
        return $this->render('tournoi/show.html.twig', [
            'tournoi' => $tournoi,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tournoi_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tournoi $tournoi, TournoiRepository $tournoiRepository): Response
    {
        $form = $this->createForm(TournoiType::class, $tournoi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tournoiRepository->save($tournoi, true);

            return $this->redirectToRoute('app_tournoi_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tournoi/edit.html.twig', [
            'tournoi' => $tournoi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournoi_delete', methods: ['POST'])]
    public function delete(Request $request, Tournoi $tournoi, TournoiRepository $tournoiRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tournoi->getId(), $request->request->get('_token'))) {
            $tournoiRepository->remove($tournoi, true);
        }

        return $this->redirectToRoute('app_tournoi_index', [], Response::HTTP_SEE_OTHER);
    }
}

symfony/templates/tournoi/_delete_form.html.twig
<form method="post" action="{{ path('app_tournoi_delete', {'id': tournoi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournoi.id) }}">
    <button class="btn">Delete</button>
</form>

symfony/templates/tournoi/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

symfony/templates/tournoi/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tournoi{% endblock %}

{% block body %}
    <h1>Edit Tournoi</h1>

    {{ include('tournoi/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_tournoi_index') }}">back to list</a>

    {{ include('tournoi/_delete_form.html.twig') }}
{% endblock %}

symfony/templates/tournoi/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournoi{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/table.css') }}">
{% endblock %}

{% block body %}
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <h1>Tournoi</h1>
                <div class="btn-group">
                    <a href="{{ path('app_tournoi_new') }}" class="btn add btn-primary add-new"><i class="material-icons">add</i></a>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Date_debut</th>
                    <th>Date_fin</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for tournoi in tournois %}
                    <tr>
                        <td>{{ tournoi.id }}</td>
                        <td>{{ tournoi.nom }}</td>
                        <td>{{ tournoi.dateDebut ? tournoi.dateDebut.format('d/m/Y') : '' }}</td>
                        <td>{{ tournoi.dateFin ? tournoi.dateFin.format('d/m/Y') : '' }}</td>
                        <td class="actions">
                            <a href="{{ path('app_tournoi_edit', { 'id': tournoi.id}) }}" class="edit"><i class="material-icons" data-toggle="tooltip" title="Edit">edit</i></a>
                            <a href="{{ path('app_tournoi_show', { 'id': tournoi.id}) }}" class="view"><i class="material-icons" data-toggle="tooltip" title="View">visibility</i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% block javascripts %}
        <script src="{{ asset('js/scripts.js') }}" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% endblock %}
{% endblock %}

symfony/templates/tournoi/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tournoi{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ block('title') }}</div>
                <div class="card-body">
                    {{ include('tournoi/_form.html.twig') }}
                </div>
            </div>
            <a href="{{ path('app_tournoi_index') }}" class="btn btn-secondary my-3"><i class="material-icons align-middle mr-2">arrow_back</i>Back to list</a>
        </div>
    </div>
{% endblock %}

symfony/templates/tournoi/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournoi{% endblock %}

{% block body %}
    <div class="card my-5">
        <h2 class="card-header">Tournoi</h2>
        <div class="card-body">
            <table class="table">
                <tbody>
                <tr>
                    <th scope="row">Id</th>
                    <td>{{ tournoi.id }}</td>
                </tr>
                <tr>
                    <th scope="row">Nom</th>
                    <td>{{ tournoi.nom }}</td>
                </tr>
                <tr>
                    <th scope="row">Date de début</th>
                    <td>{{ tournoi.dateDebut ? tournoi.dateDebut|date('d/m/Y') : '' }}</td>
                </tr>
                <tr>
                    <th scope="row">Date de fin</th>
                    <td>{{ tournoi.dateFin ? tournoi.dateFin|date('d/m/Y') : '' }}</td>
                </tr>
                </tbody>
            </table>
            <a href="{{ path('app_tournoi_index') }}" class="btn btn-secondary">Retour à la liste</a>
            <a href="{{ path('app_tournoi_edit', {'id': tournoi.id}) }}" class="btn btn-primary">Modifier</a>
            {{ include('tournoi/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}